#!/usr/bin/env sh

# ------------------------------------------------------------------
# Automatically check if a new translink archive is available to download
# if so, download and import into app
#
# Can be run as a cron task
# e.g.: 0 */12 * * 1-5 cd {project_folder} && ./auto_updates >> {project_folder}/logs/auto_updates.log 2>&1
#
# ------------------------------------------------------------------

echo "\n-----------------------------------------------\n"
echo "`date "+%Y-%m-%d %H:%M:%S"` Auto update starting ...\n"

# exec update with redirecting standard input to use default choices at user prompts
./update_gtfs --no-verbose <<STDIN -o other --options






STDIN

echo "\n\n`date "+%Y-%m-%d %H:%M:%S"` Auto update finished\n"
