#!/usr/bin/env sh

# ------------------------------------------------------------------
# Start the graphql server
#
# ------------------------------------------------------------------

pipenv run uvicorn server.server:app
