#!/usr/bin/env sh

# ------------------------------------------------------------------
# Check if a new translink archive is available to download
# Ask for user input either or not to download and import data
#
# ------------------------------------------------------------------

pipenv run python -m imports.download.check_updates "$@"
