#!/usr/bin/env sh

# ------------------------------------------------------------------
# Check for new archives on Translink website
#
# ------------------------------------------------------------------

pipenv run python -m imports.download.check_updates "$@"
